// <auto-generated />
namespace proyectoSimulacionV._1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class migracion0 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migracion0));
        
        string IMigrationMetadata.Id
        {
            get { return "202003220100112_migracion0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
